apiVersion: v1
kind: Service
metadata:
  name: falzon-me
  namespace: {{ .Release.Namespace }}
  {{- include "falzon-me.labels" . | indent 2 }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.app }}
