name: Docker

on: [push]

jobs:
  Docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: |-
        SHA=$(echo $GITHUB_SHA | cut -c 1-7)
        docker build -t ghcr.io/falzm/falzon-me:${SHA} .
        docker tag ghcr.io/falzm/falzon-me:${SHA} ghcr.io/falzm/falzon-me:latest
        docker push ghcr.io/falzm/falzon-me:${SHA}
        docker push ghcr.io/falzm/falzon-me:latest
